# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/bllon"

[social.params]
icon = "github"

[[social]]
identifier = "csdn"
name = "CSDN"
url = "https://blog.csdn.net/qq_36767214?type=blog"

[social.params]
icon = "csdn"

[[social]]
identifier = "learnku"
name = "LearnKu"
url = "https://learnku.com/blog/sosure"

[social.params]
icon = "learnku"

[[social]]
identifier = "bilibili"
name = "bilibili"
url = "https://space.bilibili.com/299210894"

[social.params]
icon = "bilibili"